name: Build Windows Binary
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install LLVM (Clang)
        uses: egor-tensin/setup-clang@v1

      - name: Configure CMake with Clang
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -G "Ninja" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

      - name: Build
        run: cmake --build build --config Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bitnet-windows-binary
          path: build/bin/Release/
